### PR TITLE
Hannahbranch

### PR DESCRIPTION
**Pull request by hannahhch**

### CODE REVIEW

**Comment by SamSteele01** [comment]
Running gives me this error.
```
./src/components/Reserve.jsx
Module not found: Can't resolve '../../ABIs/RoomRentingAbi.js' in '/home/ssteele/Documents/web3dev/BookLocal/src/components'
```

**Comment by SamSteele01** [comment]
Mine has to be:
```
require('../../abis/RoomRentingAbi.js')
```

**Comment by hannahhch** [comment]
@SamSteele01 Yeah mine has to be different for me to run it. Just change as needed.

**Comment by hannahhch** [comment]
@SamSteele01 PR updated to include "How" beginning section and "Traveler"

**Comment by SamSteele01** [comment]
Looking real good! I like the 'traveler' section a lot! I'm not sure about the light blue in 'solutions'. Maybe just white... Thoughts? Also, you need to turn off ```color="$black"``` in the very first card (search).

**Comment by hannahhch** [comment]
@SamSteele01 Fixed!

**Pull request merged**
